### ISSUE TITLE
Mô tả yêu cầu cuả đề tài.

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#1]
Triết mô tả yêu cầu và chức năng cuả đồ án. 

Tự quyết vơí Phương.

File lưu taị tệp docs/requirement.md nha.

Ta sẽ check issue hàng tuần vào 11:00 thứ Ba, và 21:00 thứ 7.

**Comment by minhtriet123** [comment]
Okay

**Comment by truongduchuy910** [comment]
Huớng dẫn trả bài: https://github.com/truongduchuy910/PBL6/blob/main/docs/submit.md
