### ISSUE TITLE
Controllers Implememt

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#20]
## Interactive

- ui/Interactive/List/Controller.js
- ui/Interactive/Item/Controller.js
- ui/Interactive/Update/Controller.js
- ui/Interactive/Delete/Controller.js
- ui/Interactive/Create/Controller.js

## Comments

- ui/Interactive/Comment/List/Controller.js
- ui/Interactive/Comment/Item/Controller.js
- ui/Interactive/Comment/Update/Controller.js
- ui/Interactive/Comment/Delete/Controller.js
- ui/Interactive/Comment/Create/Controller.js

## Reaction

- ui/Interactive/Reaction/List/Controller.js
- ui/Interactive/Reaction/Item/Controller.js
- ui/Interactive/Reaction/Update/Controller.js
- ui/Interactive/Reaction/Delete/Controller.js
- ui/Interactive/Reaction/Create/Controller.js

_if have any question, comment here._

**Comment by minhtriet123** [comment]
OKAY!!

**Comment by minhtriet123** [comment]
Interactive/comment với Interactice/reaction là có controller ui chứ riêng Interactive không cũng có ui hà Huy @truongduchuy910
