### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#3]
@minhtriet123 vẽ Class Diagram dựa trên requirement của phương nha.
làm tại ```/docs/```

Mai ta nói phương dời requiment vào docs để nó show ra website.

Ta sẽ nhắn cho Phương khi cập nhật, sẽ tạo issue cho Triết cập nhật.

Triết cập nhật sẽ tạo issue cho Kim Huy cập nhật Design.

Quy trình là thế, để ta viết ra docs.

Sau khi commit tạo pull request để ta theo dõi các commit.

**Nhớ commit hằng ngày nha**

**Comment by minhtriet123** [comment]
Okay
