### ISSUE TITLE
Relationship UI

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#31]
### ui/Relationship/Create/Button

A và B chưa kết bạn với nhau, A gửi lời mời kết bạn cho B, hoặc ngược lại

### ui/Relationship/Update/Button

A đã tạo Relationship tới B, **B chưa đồng ý (Relationship đang inActive)**
B vào tường của A sẽ thấy nút này (đồng ý kết bạn) (1)
Ngược lại thì tương tự

### ui/Relationship/Delete/Active.js

A đã tạo Relationship tới B, **B đã đồng  ý (cập nhật trạng thái Relationship là active)**
A vào tường của B sẽ thấy nút "xóa bạn"
Ngược lại thì tương tự

### ui/Relationship/Delete/Cancel.js

A đã tạo Relationship tới B, **B chưa đồng ý (Relationship đang inActive)**
A vào tường của B sẽ thấy nút "hủy lời mới" - Delete/Cancel.js
B vào tường A thấy nút "xóa lời mời" - Delete/Delete.js và  "xác nhận" - Update/Button .js : chuyển thành active (2)
Ngược lại thì tương tự

_từ (1) và (2) có thể thấy B và tường của A sẽ thấy hai nút là "đồng ý" và "xóa lời mới"_

**Comment by kimhuy011199** [comment]
A: Trần Ngọc Huy gửi lời mời kết bạn cho Nguyễn Kim Huy
B: Nguyễn Kim Huy

ui/Relationship/Create/Button.js
![image](https://user-images.githubusercontent.com/82280024/135560001-38afa27a-4411-43de-a4f9-1c3304afa39f.png)

ui/Relationship/Delete/Cancel.js
![image](https://user-images.githubusercontent.com/82280024/135560968-4b7442cb-8a5c-474b-bc14-5c17e4997c5e.png)

ui/Relationship/Update/Button.js
ui/Relationship/Delete/Delete.js
![image](https://user-images.githubusercontent.com/82280024/135561459-581276d0-2454-42e5-b18f-062b3625cfea.png)

ui/Relationship/Delete/Active.js
![image](https://user-images.githubusercontent.com/82280024/135561157-bfb634ad-d3a8-4dc0-8397-ef2c70cb9d9e.png)

**Comment by truongduchuy910** [comment]
Đúng rồi
