### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#61]
Tạo một trang pages/Test và khai báo trong pages/index.js

Import tất cả các component đã phát triển vào và render lần lượt từng cái.

Ưu tiên các *List và *Item trước.

Chạy ổn thì comment lại

Sau đó test đến các hàm *Create thử nhập và bấm tạo. Đặt *List tương ứng của bảng đó ngay bên dưới để đối chiếu.

Tương tự cho Delete và Update.

**Cái nào chạy comment lại để đánh dấu nha**

**Comment by minhtriet123** [comment]
*List comments và posts chạy ok nhưng còn hiển thị sai, thiếu thông tin. Sắp ổn, fix xong thì ổn :3
