### ISSUE TITLE
Chuyển class diagram về schemas dạng bảng trong MD

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#7]
Location: /schemas.md

- Chuyển hình vẽ thành từng bảng theo định dạng của MD
- Không ghi các trường createdBy, updatedBy, createdAt, updatedAt
- Không vẽ cơ sở dữ liệu
- Không thể hiện tính kế thừa
- Ghi rõ trường hợp phân quyền cho từng schema
- Không viết hoa chữ đầu đối với field
- Không ghi trường ID

**Comment by minhtriet123** [comment]
@truongduchuy910  Không thể hiện quan hệ luôn hả
