### ISSUE TITLE
Tính năng thích

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/PBL6#76]
Tính năng thích và bỏ thích chưa hoạt động nha

**Comment by trandiepphuong** [comment]
@minhtriet123 tính năng thích bài viết thì nhẹ nhàng, còn tính năng thích bình luận thì ta có viết hook tạo my-interactive cho bình luận mỗi khi được tạo, nên mình sẽ thêm reaction vào my-interactive của bình luận đó, chứ không thêm vài interactive của bình luận đó. Phân biệt 2 field nha

**Comment by truongduchuy910** [comment]
NNN hay sao thức khuya vậy @trandiepphuong

**Comment by trandiepphuong** [comment]
NNN ngày thứ 3 tôi nghe thấy tiếng máu chảy trong cơ thể

**Comment by minhtriet123** [comment]
@truongduchuy910  Check chỗ này giúp ta với. Issue:
- Interactive Reaction Create: UI Button/Text không nhận được giá trị truyền từ Controller qua

**Comment by minhtriet123** [comment]
@trandiepphuong  test api chưa thấy my-interactive trong comment p nghe

**Comment by trandiepphuong** [comment]
@minhtriet123 pull code về, xong chạy trên local graphql thì được chứ chưa deploy lên odanang.net, nên khi mi tạo bằng frontend sẽ chưa được

**Comment by minhtriet123** [comment]
@trandiepphuong oke
